# Generated by Django 4.1.2 on 2022-10-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sihas', '0001_initial'),
    ]

    operations = [

    ]
