# Generated by Django 4.1.2 on 2022-11-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sihas', '0002_alter_siha_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sihas',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sihas',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
