# Generated by Django 4.1.2 on 2022-10-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listings',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='listings_id',
            new_name='listing_id',
        ),
    ]
