# Generated by Django 4.1.2 on 2022-10-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='photo_6',
            new_name='photo_4',
        ),
    ]
