# Generated by Django 4.1.2 on 2022-11-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings', '0002_rename_photo_6_listings_photo_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='auto_antenna',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='country',
            field=models.TextField(max_length=200),
        ),
    ]
